In [1]:
import pandas as pd

In [2]:
df_orig = pd.read_pickle('../data/.pkl')
df_orig.shape

(516406, 40)

In [4]:
df_orig.head(1).T

                                                   905425
CASE_ENQUIRY_ID                              101001983786
OPEN_DT                               2017-01-07 10:51:37
CLOSED_DT                             2017-01-07 11:46:43
TYPE                             Request for Snow Plowing
SubmittedPhoto                                       True
LOCATION_ZIPCODE                                     2124
Property_Type                                     Address
LATITUDE                                          42.2809
LONGITUDE                                         -71.068
Source                               Citizens Connect App
description                                           NaN
COMPLETION_HOURS_LOG_10                        -0.0369997
tract_and_block_group                             1004002
queue_wk                                            55026
queue_wk_open                                           1
race_white                                       0.242399
race_black                                       0.514358
race_asian                                       0.035473
race_hispanic                                   0.0675676
race_other                                       0.140203
poverty_pop_below_poverty_level                         0
earned_income_per_capita                            34340
poverty_pop_w_public_assistance                 0.0597484
poverty_pop_w_food_stamps                        0.138365
poverty_pop_w_ssi                               0.0597484
is_description                                      False
zipcode                                              2124
neighborhood_from_zip                          Dorchester
school                                      15_hs_diploma
school_std_dev                                    91.7672
housing                                               own
housing_std_dev                                   26.8701
bedroom                                                 3
bedroom_std_dev                                   61.5123
value                                              350000
value_std_dev                                     20.9794
rent                                                 1750
rent_std_dev                                      19.1622
income                                             112500
income_std_dev                                    28.6167